function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("click") and action.pressed then
		print("Click!")
		msg.post('/outfit/visual#outfitController', 'set pants', {color = vmath.vector4(1,0,.8,1)})
		msg.post('/outfit/visual#outfitController', 'set shirt', {color = vmath.vector4(.5,0,.8,1)})
		msg.post('/master#wardrobe', 'hello')
	end
end